version: '3'

services:
  neo4j:
    # tested on neo4j version 4.4.4
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      # - NEO4J_USERNAME=neo4j
      # - NEO4J_PASSWORD=neo4j
      # hack on disabling username/password for demo purposes
      - NEO4J_dbms_security_auth__enabled=false
